# Site settings
title: "Adarsh Karayathingal ğŸ‘¨ğŸ»â€ğŸ’»"
description: My Blogs
author: r4pt3r
email: adarshk460@gmail.com
twitter_username: adarsh_k_
github_username: r4pt3r

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://r4pt3r.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-128242584-1
disqus_id: r4pt3r

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

